# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: todgru's Range Rover Classic
email: todgru@gmail.com 
description: > # this means to ignore newlines until "baseurl:"
  Information and resources for the 1992 Landrover Range Rover Classic
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://rangeroverclassic.github.io" # the base hostname & protocol for your site
twitter_username: todgru 
github_username: todgru

# Build settings
markdown: redcarpet
redcarpet:
  extensions: ["no_intra_emphasis", "tables", "autolink", "strikethrough", "with_toc_data"]
