# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Range Rover Classic
email: todgru@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  Information and resources for the Land Rover Range Rover Classic.
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://rangeroverclassic.github.io" # the base hostname & protocol for your site
github_username: todgru

# Build settings
markdown: GFM

destination: ../_range-rover-classic_site
exclude: [manuals/*.pdf, manuals/*.zip]

cats:
  - name: about
    desc: How to contribute!
  - name: alternator
    desc: Repair and replacement, symptoms and issues
  - name: body
    desc: You'd be suprised at how much steel is under those aluminium panels
  - name: brakes
    desc:
  - name: chassis
    desc:
  - name: check engine light
    desc: Common issues and easy fixes
  - name: ecu
    desc: Brains of the 3.9l motor
  - name: engine
    desc: 3.9l Petrol and Diesel
  - name: exhaust
    desc:
  - name: electrical
    desc: What does this wire do?
  - name: fluids
    desc:
  - name: maintenance
    desc: How do I change the oil?
  - name: manuals
    desc: PDF's UPDATED 2020/July
  - name: repair
    desc: How-to's
  - name: replacement
    desc:
  - name: suspension
    desc:
  - name: tires
    desc:
  - name: transfer case
    desc:
  - name: transmission
    desc:
  - name: troubleshooting
    desc:
  - name: wheels
    desc:
